name: Update data

on:
  schedule:
    - cron:  '0 * * * *' # runs every hour
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Prepare data
      run: |
        python fetch_data.py
        echo ${{ github.run_id }} > latest_run_id.txt
    
    - name: Check if there are changes in the repo
      run: |
        git status --porcelain
        if [[ -z $(git status --porcelain) ]];
        then
          echo "Repo is clean"
          echo '::set-output name=changed::0'
        else
          echo "Repo is dirty"
          echo '::set-output name=changed::1'
        fi
      id: changes
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: data
        path: data.pkl
        
    - name: Commit and push to repo
      if: steps.changes.outputs.changed == 1 # only try to commit if there are actually changes
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: main
        name: GitHub Action Bot
        commit-message: Update latest_run_id.txt
        rebase: 'true'
